baseURL = "https://devopsctl.com/"
languageCode = "en-us"
title = "Kosli's Software Development Lifecycle"

[taxonomies]
  risk = 'risks'
  level = 'levels'

[params]
  company = 'Kosli'
  csor = 'Kosli'
  vcs = 'git'
  vcsHost = 'github'
  forkLink = 'https://github.com/kosli-dev/devopsctl/fork'
  logo = 'svg/logo.svg'
  BookSection = '/'

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3
